# Generated by Django 3.0.8 on 2024-01-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_auto_20240107_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology Engineering', 'Information Technology Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Masters of Computer Applications', 'Masters of Computer Applications')], max_length=100),
        ),
    ]
